export { Home as PageHome } from "./Home"
export { List as PageList } from "./List"
export { Layout as PageLayout } from "./Layout"
export { default as AdmPage } from "./Adm"
export { Login as LoginPage } from "./Login"
export { Cadastrar as RegisterPage } from "./Cadastrar"
